### ISSUE TITLE
wrong amount of perk points in slaves

### ISSUE THREAD

**Issue by RandomNecromancer** [Innoxia/liliths-throne-public#1016]
slaves, after being captured, have a wrong initial amount of perk points, which can be fixed, however, by resetting their perk points. (version 0.3)

**Comment by aDrunkLittleDerp** [comment]
I've had this issue as well. I don't know if it's affecting everyone, or just those who are using difficulties with level scaling NPC's.

I've also noticed that this can affect the player character, too. Though resetting it doesn't always fix it. I have a Level 45 Slave who has -679 points, reseting it set it to -615. My elemental is at 489 points, and resetting it just gave 594...

**Comment by Dtar316** [comment]
yeah i also had it happen to have negative points on my player character, happens far too often for my liking because my perk tree is never completed when it occurs, could care less if my tree was full lol. Honestly, lowest level i've seen it happen is lvl 10 on the pc, been trying to reliably reproduce it though so i know wat to avoid doing

**Comment by DrZed** [comment]
#1020 
Found the issue
