### ISSUE TITLE
Suggestion: Litter Size Rework

### ISSUE THREAD

**Issue by TheWeirdling** [Innoxia/liliths-throne-public#1092]
Currently we have two traits tied to increasing a character's offspring counter per pregnancy:  Seeder and broodmother.  Both these traits seam overly simplified for this particular kink, especially considering how variable fluid production has become.  Perhaps this is already planned but I have not seen it mentioned previously.

I suggest that both these traits' effects be tied to a characters penis (testicles) or vagina (womb) with different races having different default values.

For vaginal values it could be as simple as a maximum/minimum offspring count per pregnancy and work similarly to before.

For penis values the system might be reworked to focus on monozygotic twins (i.e. identical twins) and be a percent chance for each child in a current pregnancy to double into identical twins.  

As an example, say a particular character's womb will have between 2-4 children per pregnancy.  The game asks the RNGs (random number gods) for a value and gets 3.  Next the game takes the characters monozygotic twins chance value (this needs a better name), in this example 30% and checks it three times, once for each child.   For each positive it then adds another child that is identical to one of the previous ones, in this case say one positive. The resulting pregnancy would then have 2 non-identical children and one set of identical twins for a total of 4.

It may also be worth making the monozygotic algorithm recursive, perhaps dropping the chance each time a positive is rolled so that it is possible to get triplets, quadruplets, etc.

In each case these values could then be modified by transformation potions and give more control to the player in how a particular character's pregnancy/impregnation effects work.

**Comment by jetharius** [comment]
The first half of what you asked is already true, the race class includes a minoffspring and maxoffspring variable for each race with some being more... fertile than others.  The two perks are just flat multipliers on the max value that can be generated.  So a human seeder conceiving with a human broodmother would be min(1), max((1)*2)*2 for a total spread of 1 to 4 possible children.  Adding the possibility of identical twins would require implementation in the way offspring are generated, ensuring that multiple NPCs would have the same exact same physical attributes at generation.     

 Alternatively a much easier option would be including a simple implementation of an additive variable tied to a consumable/enchantment for the maximumNumberOfChildren variable that is checked during litter size computation.  However I feel that should be restricted to the one conceiving.

I want to think that adding a "fertility period" would fill your need best, where instead of the base calculation of virility * fertility produces either a true or false on conception and then litter generation happening, individuals that can conceive have a period of time where they are "fertile" and a number of possible eggs are produced based on fertility score/perk/augments and then after copulation for each min/hour of game time that the individual retains virile fluid there is a roll of the father's virility/perk/augments against each of the possible eggs.  This will give more value to the amount of ejaculate and the amount of time between copulation and conception instead of conception happening instantly at time of ejaculation.  This would also allow potentially multiple fathers from a single pregnancy.

**Comment by TheWeirdling** [comment]
I think I was a bit unclear previously, I think the brood-mother and seeder perks should be incorporated into the standard character statistics, like fluids, size, colors etc.  Currently they are perks disconnected from the game's standard framework.  What they modify (maximum offspring count) isn't so interesting as to be game changing which suggests they should simply be genital statistics that are modifiable with a potion.
