### ISSUE TITLE
"Cum Regeneration" enchantment in clothing has no effect.

### ISSUE THREAD

**Issue by Rawrior** [Innoxia/liliths-throne-public#1152]
Clothing with "regeneration" boosted in some fashion does not seem to update the actual cum regeneration value in any instance. The prompt that regeneration has increased triggers, but is never reflected in the actual values on the character.
I think it _may_ also count for potion enchantments if not using the enchantment tied to penis effects.

Steps to reproduce:
1. Have character with penis
2. Note cum regeneration value
3. Enchant an item with "regeneration" set to a high value and equip.
4. Rest in room a couple of times. Take note of prompts indicating cum regeneration should have increased.
5. Note cum regeneration value

Expected outcome: Cum regeneration increases.
Actual outcome: Cum regeneration does not increase.

**Comment by A-haron** [comment]
Just checked.

It increases, but with "mayor boost" it's adding a 1 _ml/day_ to the default value (10000 _ml/day_). The potency defines the frequency, not the increment, so the effect is very slow to notice in the stats screen, which shows one decimal of _ml/minute_, meaning you need _24*60/10 = 144_ increments to see a change in that number (0.1), if my maths are correct.

The issue here is not the effect of the enchantment, but the amount of it, or the way the game displays it.

Possible that seems possible to me right now are:
1. Changing the number of decimal displayed on the stat screen.
2. Changing the unit itself (From ml/minute, to ml/hour, reducing the necessary increments to _24/10 = 2.4_, but displaying bigger numbers).
3. Tweaking the increase values to be more noticeable.
