### ISSUE TITLE
Orgasmic Level Drain never triggers

### ISSUE THREAD

**Issue by Rydelfox** [Innoxia/liliths-throne-public#1279]
**Describe the bug**
During sex scenes, the perk Orgasmic Level Drain never appears to trigger. When your partner orgasms, "Level drain:ON" will sometimes appear, but grayed out and the tooltip indicates "<name> cannot have <his/her> level drained."  The description of the tooltip in this button makes it sound like one of your needs the dominant fetish and the other need submissive (which isn't mentioned in the perk tooltip), but arranging this doesn't change anything.

**Expected behavior**
With the Orgasmic Level Drain perk, when your partner orgasms, you would drain a level and gain experience

**To Reproduce**
1. Take the Orgasmic Level Drain perk
2. Have Sex
3. Have your partner orgasm
4. Level Drain option would be available and, if on, would drain a level from your partner, giving you experience

**Attach files**
![Level Drain Fetish](https://user-images.githubusercontent.com/6630535/72209575-ff7a8f80-347d-11ea-9ea1-1b02ef8f4fbe.png)
![Level Drain No Fetish](https://user-images.githubusercontent.com/6630535/72209576-ff7a8f80-347d-11ea-93e4-eeb5b9cfcabe.png)

Note that in the latter, the PC has the Dominant fetish, but fetishes don't seem to appear in the side bar for the PC. I don't recall if that happened in previous versions or not

**Additional information:**
 - Game version: 0.3.5.9
 - OS: Windows 8.1
 - Using .jar
- Java 1.8.0_231 (64-bit)

**Comment by Questiondeca** [comment]
Something I've noticed is that only _**persistent**_ NPCs seem to be able to be drained at this time, that's Brax/Bree, Candy, etc. NPCs that can be dismissed from the game don't currently appear to be drain-able in most if not all circumstances.

**Comment by Rydelfox** [comment]
Odd - looking at the code, it seems like it should be the opposite - isImmuneToLevelDrain() returns !this.isUnique()

**Comment by Questiondeca** [comment]
So, I pulled up my build of 0.3.5.10 (which is what is currently available as code in the Dev Branch), and this seems to be fixed in that build... however, I had great difficulty testing that fact in game as for some reason there were no random spawns beyond children. (Random Items still appeared occasionally but no non-child NPCs that weren't already available in Dominion spawned).

It appears to be a return to the null pointer exception errors.
[error.log](https://github.com/Innoxia/liliths-throne-public/files/4056643/error.log)

**Comment by Rydelfox** [comment]
The code I was checking was in Dev, since the main branch doesn't seem to have this perk yet, so it may already be fixed in that case.

**Comment by Questiondeca** [comment]
I concur, still, I'd recommend leaving this open till the Main branch catches up and we have a stable build to confirm with.

**Comment by Fortilicious** [comment]
I've done some extensive testing and spoke with others in the discord and these are my findings:  Game difficulty mode matters.  On normal difficulty, random npcs and persistant npcs are all drainable down to a pre-set minimum level (Lilaya's is lvl 1).  This is apparently exploitable when used on elementals since elementals level up alongside you.

On Morph difficulty, it seems different.  Each NPC can be drained once and only once, for one level, no matter how many climaxes you give them.  However, it is also glitched in that per the rules of the increased difficulty, the NPCs also level up alongside you.  Draining them causes you to level, which causes them to level and they suffer no level penalty.

Note that some NPCs cannot be drained at all, noticeable on **_NPCs that have no level_** (brothel customers, being an example).

**Comment by Rydelfox** [comment]
Confirmed fixed in the current version.
