### ISSUE TITLE
0.3.6.9 - Glory hole variable typo

### ISSUE THREAD

**Issue by LeechingLecher** [Innoxia/liliths-throne-public#1311]
In the warehouse using the glory hole:

" Letting out a lewd squeal, INVALID_TARGET_NAME(ncp) impatiently encourages you to get started"

Looks like a simple typo - guessing it should be "npc".

**Comment by AceXP** [comment]
This has been fixed for some time (since version 0.3.7.3). Could you check it and close this issue?

**Comment by LeechingLecher** [comment]
I kind of these tickets to be closed when fixed, but sure. Just tested, seems fixed.

**Comment by AceXP** [comment]
Thanks. The reason it was not closed earlier are twofold. First, it may have been reported here, but also in the blog, in the discord channel or in a message to Inno. So that makes it difficult to track each issue. Second, only Inno or the person who created the issue can close it, and Inno's time is better spent creating new stuff ;-)
So right now I am going through the issues here, and asking people to close issues that are done, or fixing/proposing a fix for those that still need doing.
