### ISSUE TITLE
Coverings on a character's face are always the same as the coverings on their body.

### ISSUE THREAD

**Issue by Freimann01** [Innoxia/liliths-throne-public#1363]
**Describe the bug**
If you change a character's head to be a a different species than their body, the covering on the face will be the same as the covering on the body. For example, if you have a horse's face and an alligator body, you will have an equine face covered in scales. 

 Game version: 3.8.6
 - OS: Windows 10
 - .jar
- java 1.8.0_241

**Comment by prold** [comment]
I think this is not a bug. When you choose a body for a character, you choose the whole body in General, not just the torso. So, in the head tab, you do not select the head, only the face, but the head automatically adjusts to the body so that the resulting creature looks +- adequate. The covering of the face can not differ from the covering of the head, because it is on the head and is located.
