### ISSUE TITLE
Milking Room Only Allows 7 Slaves At A Time

### ISSUE THREAD

**Issue by GreatSwordOfVictory** [Innoxia/liliths-throne-public#1424]
The Milking Room description says that up to 8 slaves can be using it at a time, but in game you can only assign 7 slaves at a time. Might be because the game saves one of the "spots" for player use? Because 7 slaves + 1 player = 8 total? So I wasn't sure if it was a bug or a error in the room's description text, but figured I'd point it out here.

**Comment by AceXP** [comment]
It would seem to be a bug, as the intention seems to be to disallow the player the use of the room if it is fully occupied with 8 slaves.

**Comment by AceXP** [comment]
I've looked into this, and I think that everything works as expected. You can assign 8 slaves to each milking room. It's just that AFTER you've assigned the eight slave, the time slots for that slave will grey out for the Dairy Cow job, and the tooltip will say 'not enough space in milking rooms'. But that is logical, since this slave is now occupying the last available slot, so it's not available for another slave. But the slot DOES show the yellow color for that job, and the slave IS assigned to it at that time. Also, when you visit the milking room at an appropriate time, all the eight assigned slaves will be there.
I had 7 slaves on 24hr duty, and three other slaves each working 8 hours and that works just fine. I am sure other combinations will work too.
Could you check this and close this issue if you agree?

**Comment by GreatSwordOfVictory** [comment]
That's what I'm seeing too, glad I'm not going crazy lol. Not sure if the 8th slave assigned is having their fluids milked or not. I would check right now but I have to run and do IRL stuff. If nobody else can verify before I get back, I'll try poking around the issue more to see if I can find anything else out.

**Comment by GreatSwordOfVictory** [comment]
Alright, I think AceXP got it right when he said something funny is going on. So, you can assign 8 slaves to be milked. That is working properly. The thing is, only 7 slaves are in the milking room during their assigned times, the whole time. There's some weirdness going on with the 8th slave, and what I saw was that at the first hour, every slave went in. At the second hour, the 8th slave left and went back to their room, where they had the milking stuff equipped like they were in the milking room. The good news is that the game seems to still track the fluids being milked properly, so you don't loose out on any money or whatever.

I have no idea what kind of black magic makes this game work, but to my baby programmer brain, this makes me think something's wrong with how the milking room handles having more than 8 slaves or something, making it boot the 8th slave back to their room when it's not supposed to. It's weird, haha.

**Comment by GreatSwordOfVictory** [comment]
Going to close this, AceXP made a pull for it and it seems like the issue is more or less going to be taken care of. Thanks guys!
