### ISSUE TITLE
Incorrect forced raccoon TF

### ISSUE THREAD

**Issue by Kon1399** [Innoxia/liliths-throne-public#1497]
**Describe the bug**
Whenever I encounter raccoon-morph with transformer fetish, who wants to transform me in raccoon, It doesn't work. There is only text shown but with no actual effect.

**Expected behavior**
Correct forced transformation.

**Additional information:**
 Windows 10
Game ver. 0.3.15

**Comment by AceXP** [comment]
There is a bug in the raccoon subspecies .xml file: (res/race/dsg/raccoon/subspecies/raccoon.xml)

Where it says `transformativeItemId` it should be `dsg_race_raccoon_popcorn`, and where it says `attributeItemId` it should be  `dsg_race_raccoon_cotton_candy_soda`. 

If you want, you can change this file yourself to fix the bug. It should also be fixed in the next version.

**Comment by AceXP** [comment]
This is fixed in the 0.4.0 version, could you check it and close this issue?
