### ISSUE TITLE
(0.3.19) Player Youkos can access the slime tf menu.

### ISSUE THREAD

**Issue by master9147** [Innoxia/liliths-throne-public#1512]
Player Youkos can access the slime tf menu when they shouldn't/

**Comment by AceXP** [comment]
Yes. It's known, which is why there is a PR (#1506) to fix it. That PR has not been merged yet, so it's still possible in the current version. But please note that there is no official way for the MC to become a Youko themselves in the game. It can currently only happen by using the debug menu. So strictly speaking, there is no need to fix it yet.

**Comment by master9147** [comment]
> 
> 
> Yes. It's known, which is why there is a PR (#1506) to fix it. That PR has not been merged yet, so it's still possible in the current version. But please note that there is no official way for the MC to become a Youko themselves in the game. It can currently only happen by using the debug menu. So strictly speaking, there is no need to fix it yet.

So are you asking me to close this?

**Comment by AceXP** [comment]
No, I just wanted to make sure the reason why it's not fixed yet is clear.

**Comment by AceXP** [comment]
This is fixed in the 0.4.0 version, could you check it and close this issue?
