### ISSUE TITLE
Unable to join Discord server

### ISSUE THREAD

**Issue by Wpolina** [Innoxia/liliths-throne-public#1670]
**Unable to join Discord server**
I am met with the "Whoops... unable to accept invite" message after clikcing the Join server button.

**Expected behavior**
Join the server.

**To Reproduce**

1. Go to '(https://lilithsthrone.blogspot.com/?zx=86ec7431fd328f6e)'
2. Click on 'Discord on the right side'
3. Select "continue to discord"

**Attach files**
Screenshot of the discord error attached.

**Additional information:**
 - A few months ago my Discord account was hacked but is secure again with mfa setup.
 - OS: Windows 10
-Discord tag: Wpol#0285

![Invite failed](https://user-images.githubusercontent.com/106993997/172216832-cd3a4f58-1c06-4ae6-8212-963c16ccf608.png)

**Comment by CognitiveMist** [comment]
There are a few known reasons for this happening:
1. The invite is exhausted, expired, invalid or revoked.
   - The invite on the blogspot is infinite, so this probably isn't the issue.
2. You are banned.
   - Unlikely if you've never joined the server before.
   - If you were in the server when your account was hacked, you might be banned because of that. A server admin will have to unban you, then.
3. You are at the server limit.
   - Discord only allows being in 100 servers at a time. If this is the case, you'll have to leave a different server first.

It's possible it's something else, but that would probably be a question for Discord support.

**Comment by Wpolina** [comment]
How might I come into contact with a server admin?

**Comment by CognitiveMist** [comment]
You should be able to dm `Innoxia#0097`, who is the server owner.

Edit: upon reflection, I don't really know how to do that myself. I'll ask one of the moderators to look at this request here, but no promises that they'll reply.

**Comment by Innoxia** [comment]
@Wpolina Your account had been banned after being hacked and then spamming scam links. I've unbanned you just now, so you should be able to rejoin the server. Please send me an email or reopen this issue if the problem persists.
