### ISSUE TITLE
extreme performance and gameplay bug

### ISSUE THREAD

**Issue by Moth-GITHUB** [Innoxia/liliths-throne-public#1726]
hard to explain but I think it's to do with java update, started playing game again after new java update (the recent one a few days ago, don't remember what the previous version was but this is version 8 update 351 (1.8.0_351-b10)

mostly qol issues with this bug, to do anything you need to press keyboard keys instead of clicking on phone you need to press p, esc for menu, f5 to save. the stuff that makes playing with mouse not fun.
tool tips don't disappear/ they appear in the middle of the screen.
last time I played everything was well after recent update to java everything got basically fucked

appologies if this doesn't fit standard bug report template

**Comment by CognitiveMist** [comment]
There's been issues with the past few Java updates, sad that it seems to be getting worse 😞 

Most people just play with the version packaged with the exe version: Java 8 update 172, which avoids these issues. (If you're on Windows, the easiest way is to use the exe version instead, otherwise you'll have to either replace your system java, or install two Javas and launch the game with specifically 172)

**Comment by Moth-GITHUB** [comment]
well damn.
