### ISSUE TITLE
(0.4.7) jar Not running

### ISSUE THREAD

**Issue by bjkim9805** [Innoxia/liliths-throne-public#1746]
**Describe the bug**
Lilith's Throne 4.7.0(jar) is not runnable.

**Expected behavior**
It needs to open program normally.

**To Reproduce**
run LilithsThrone_0_4_7.jar

**Attach files**
com.lilithsthrone.main.Main cannot be found or loaded.
java.lang.NoClassDefFoundError: javafx/application/Application

**Additional information:**
 - Game version 0.4.7
 - OS: Win10 x64 / MacOS 12.6 x64
 - Using .jar or .exe: jar
- If using .jar, and you are not including an error.log file/text, please include your java version: [e.g. 1.8.0_172]
win10
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment Microsoft-25199 (build 11.0.12+7)
OpenJDK 64-Bit Server VM Microsoft-25199 (build 11.0.12+7, mixed mode)

macOS
java version "19.0.1" 2022-10-18
Java(TM) SE Runtime Environment (build 19.0.1+10-21)
Java HotSpot(TM) 64-Bit Server VM (build 19.0.1+10-21, mixed mode, sharing)

 - etc : exe version successfully working on win10

**Comment by CognitiveMist** [comment]
That error means that the JavaFX dependency was not found

Since the report lists both Win 10 + Java 11, and MacOS + Java 19:
- Oracle Java 9 and later, or any version of OpenJDK, require JavaFX. (This is the error you are currently seeing).
- Java 15 and later require a third party Nashorn that is different from the built-in Nashorn from older Javas. Currently, the official releases only support the older Javas.
- MacOS typically requires running the game via the terminal or a shell script.

Recommendation: get Java 11 and JavaFX, then run the game via a command like `<java>/bin/java --module-path <javafx>/lib --add-modules=javafx.controls,javafx.fxml,javafx.web -jar <lt>`, where:
- `<java>` is replaced by the installation path of Java 11
- `<javafx>` is the installation path of JavaFX
- `<lt>` is the game jar file

**Comment by bjkim9805** [comment]
> That error means that the JavaFX dependency was not found
> 
> Since the report lists both Win 10 + Java 11, and MacOS + Java 19:
> 
> * Oracle Java 9 and later, or any version of OpenJDK, require JavaFX. (This is the error you are currently seeing).
> * Java 15 and later require a third party Nashorn that is different from the built-in Nashorn from older Javas. Currently, the official releases only support the older Javas.
> * MacOS typically requires running the game via the terminal or a shell script.
> 
> Recommendation: get Java 11 and JavaFX, then run the game via a command like `<java>/bin/java --module-path <javafx>/lib --add-modules=javafx.controls,javafx.fxml,javafx.web -jar <lt>`, where:
> 
> * `<java>` is replaced by the installation path of Java 11
> * `<javafx>` is the installation path of JavaFX
> * `<lt>` is the game jar file

This works! thanks!
