### ISSUE TITLE
Can't delete the game

### ISSUE THREAD

**Issue by ghost** [Innoxia/liliths-throne-public#1828]
I tried out this game and it wasn't for me, but every time I try to get rid of it I get a popup saying "The action can't be completed because the folder or a file in it is open in another program." even though I don't have it open. Any help will be much appreciated.

**Comment by Moth-GITHUB** [comment]
try restarting your PC then deleting the folder.
also are you using jar or exe?

**Comment by ghost** [comment]
Tried that, didn't work. 
I'm using exe.

**Comment by Moth-GITHUB** [comment]
I'm gonna assume you use windows then. try ending the game via task manager or by instead of like closing the game with X use the quit button maybe (unless that is what you were doing before hand at which try vice-versa)
apart from that any other advice I can give is to like try end tasking multiple other things maybe which the game uses to try and see if it quits it.
also just an important question because I haven't had the issue before, where did you download the game?
did you make sure it was from an offical and safe source? such as the blog or the github page?

**Comment by ghost** [comment]
I've tried doing that as well.
I have no idea what other things the game could be using.
I can't remember where I downloaded it.

**Comment by Moth-GITHUB** [comment]
from my knowledge the exe uses a different version of java so try end tasking any java operations running.
also depending on your browser you can check the download history. Ctrl+j on firefox unsure for other browsers but it does also show the website you downloaded it from (I've attached an example.)
![example](https://github.com/Innoxia/liliths-throne-public/assets/104662342/aca7b895-7c2b-4b38-bb34-3d536232420f)
also if you do happen to be using windows I should have mentioned this earlier but this could also help with you issue possibly
https://support.microsoft.com/en-gb/windows/start-your-pc-in-safe-mode-in-windows-92c27cff-db89-8644-1ce4-b3e5e56fe234#WindowsVersion=Windows_10

**Comment by ghost** [comment]
Safe Mode worked! Thank you so much for the help. ^^

**Comment by teeber** [comment]
this is so funny in 2025))) there is programm called "unlocker" it existed for decades.
use it to delete anything.
