### ISSUE TITLE
Mystery Kink turned into Succubus's Kiss

### ISSUE THREAD

**Issue by Lytrigian** [Innoxia/liliths-throne-public#1841]
**Describe the bug**
Both the description and the effects of Mystery Kink are the same as Succubus's Kiss. It seems to happen irrespective of save. I loaded up a save from a previous playthrough and saw the same issue.

**Expected behavior**
Mystery Kink ought to bestow a random fetish, not give +50 lust, +50 arousal

**To Reproduce**
Have both in your inventory and look at them.

**Attach files**
error.log contents pasted under Additional Information. Screenshots attached.

**Additional information:**
Game Version: 0.4.10.7 (exe64)
Java: 1.8.0_172 (Oracle Corporation)
OS: Windows 10 (amd64)
Mod folders present: innoxia
![Screenshot 2024-12-18 004253](https://github.com/user-attachments/assets/539a4ea0-7d54-426c-b178-87a08860fb8a)
![Screenshot 2024-12-18 004306](https://github.com/user-attachments/assets/1d265f25-0467-4480-9a41-fc143564c492)

**Comment by SightglassCat** [comment]
Not really a bug. Item was changed in v0.4.10 to give lust and arousal instead of a random fetish when left un-enchanted.
https://github.com/Innoxia/liliths-throne-public/blob/dev/res/patchNotes/20240531-patchnotes-0.4.10.html
Items already in an inventory are not renamed when the item type's name is changed.
