### ISSUE TITLE
0.2.4 - School of Water ability does nothing

### ISSUE THREAD

**Issue by LeechingLecher** [Innoxia/liliths-throne-public#381]
Without School of Water, an elixir to make milk taste like chocolate lists a base cost of 2, 6 to add the effect, and final cost of 8. It does drain 8.

With Ice Shard known, the same elixir lists a base of 2, 0 to add the effect, but lists a final cost of 8. It does drain 8.

With Transformer all the numbers are halved, but the School of Water ability still just makes the effect appear to cost 0 to add, while still adding the full price.

**Comment by FlamingFool** [comment]
To expand on this now having looked at the code, it appears as if it could be caused by properly calculating the discount when previewing the cost of the specific enchant but the actual cost of the final item is being handled separately by something that isn't applying that (*0) discount to that specific enchantment.

This appears to be the reverse of a bug I noticed in 0.2.3.5 where when enchanting clothing with the half cost perk the individual enchantments would never be discounted but the final result was discounted. This was probably a result of the enchantments not being discounted but the final cost getting a (*0.5) multiplier. The result was correct but half of the UI implied there was no discount.

After sorting through the source I would hazard a guess that this would be solved by adding a check that looks something like
```java
if(Main.game.getPlayer().isSpellSchoolSpecialAbilityUnlocked(SpellSchool.WATER) && ingredient instanceof ?????)
{
	cost*=0
}
```
somewhere around line 172 in[EnchantingUtils.java](https://github.com/Innoxia/liliths-throne-public/blob/master/src/com/lilithsthrone/game/inventory/enchanting/EnchantingUtils.java). However to make an entire potion type free could be game breaking it might be more better to make specific effects free which could be done as
```java
for(Entry<ItemEffect, Integer> entry : effectCount.entrySet())
{
	//cost += entry.getKey().getCost() * Math.abs(entry.getValue());
	cost += entry.getkey().getModifierEffectCost(ingredient, entry) * Math.abs(entry.getValue());
}
```
This would use the existing code in line 125 of [EnchantingUtils.java](https://github.com/Innoxia/liliths-throne-public/blob/master/src/com/lilithsthrone/game/inventory/enchanting/EnchantingUtils.java) which appears to already account for the Water school passive. *getModifierEffectCost* also appears to account for **CLOTHING_ENCHANTER** and **FETISH_TRANSFORMATION_GIVING** cost reductions by discounting all of the effects individually instead of just waiting until the end which would make the If statements at lines 166 and 169 apply the discount a second time.

I suspect that *getModifierEffectCost* is being called when previewing the modified cost of the enchantment, producing the correct intended value, but using *getCost()* instead when calculating the final cost is using the raw cost which is not always accurate with the addition of the Water Passive Ability. This may have been noticed sooner if **CLOTHING_ENCHANTER** and **FETISH_TRANSFORMATION_GIVING** were not being checked for at both lines 125 and 166

**Comment by LeechingLecher** [comment]
Think this was fixed quite some time ago. Certainly seems so on 0.3.9.8
