### ISSUE TITLE
Getting addicted to lupine cum describes it as human cum

### ISSUE THREAD

**Issue by Nenoxx** [Innoxia/liliths-throne-public#526]
**Version** : 0.2.5.8
**From** : Discord
**Date** : 22 May 2018

*"there was another bug I ran into last night im trying to remember it and find it x_x
oh right, when I got addicted to my slaves girlcum it said I was craving human girlcum, they are a greater wolf morph and I had JUST applied the TF potion to give them a pussy using a wolf potion"*

**Comment by A-Master-of-Puppets** [comment]
This looks like the same issue as #502 and #509, and possibly others.

**Comment by ThatWhichLurks** [comment]
Did a little experimentation, and as far as I can tell the species tag on girlcum doesn't get switched by pussy TFs, ever.  Not sure what's up with any reports of other fluids displaying the bug, as I've only ever seen it for girlcum (and it happens every time for that).  Any character generated without a pussy has human girlcum, regardless of transformations; any character generated with one has the original species' girlcum, again regardless of transformations.  Even slime self-TF (PC or slave) doesn't seem to update it. It's easiest to see with addictive and/or psychoactive girlcum on a squirter (due to the status icon and/or hallucinations, respectively), but I've tracked it through exports of characters regardless of those modifiers.
