### ISSUE TITLE
Losing/Submitting Only Results in Mugging

### ISSUE THREAD

**Issue by soupbowlhat** [Innoxia/liliths-throne-public#915]
Even if I use a completely clean exe folder and don't change anything, losing random encounters never ends in anything other than losing a bit of money. I didn't find anything else talking about this and it doesn't seem to be in patch notes for later versions, so sorry if this is already noted. The version I'm using is v0.2.10.2 and is the pre-zipped .exe, if that helps.

**Comment by IvoryOwl92** [comment]
1. NPCs have gender preferences. If you're a guy and come across a lesbian or hetero dude, neither of them are going to have sex with you. Exception being during arcane storms.

2. This is just an assumption but I believe you need to have non-con turned on otherwise alley encounters are just robberies and not sexual assaults.

**Comment by CognitiveMist** [comment]
I've always thought that was a weird change.
